steps:
#Copy
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_SIGNING_BUCKET_PATH}','.']
  id: copy_signing_files
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_FABRIC_API_SECRET_BUCKET_PATH}', 'app']
  id: copy_fabric_files
#Copy the build cache locally, if it exists.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '${_ANDROID_BUILD_CACHE}/', '/build_cache']
  id: copy_build_cache_local
  volumes:
    - name: 'build_cache'
      path: '/build_cache'
- name: 'ubuntu'
  args: ['mkdir', 'licenses']
  id: licenses-directory
#Copy whatever licenses we have to the licenses directory 
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: "bash"
  id: copy_licenses
  args: 
  - '-c'
  - |
    gsutil rsync -d -r "${_LICENSES_BUCKET}" licenses || exit 0
  waitFor: 
  - licenses-directory
#Android build and distribute with gradle
- name: 'gcr.io/$PROJECT_ID/android-builder'
  args: ['gradle-build','${_ANDROID_SDK_LICENSE}','-PbetaDistributionGroupAliases=${_EMAIL_DISTRIBUTION_GROUP}','assemble${_BUILD_TYPE_CAPITALIZED}','crashlyticsUploadDistribution${_BUILD_TYPE_CAPITALIZED}']
  id: gradle_build
  waitFor:
    - copy_licenses
    - copy_build_cache_local
    - copy_signing_files
    - copy_fabric_files
  volumes:
    - name: 'build_cache'
      path: '/build_cache'
#Repopulate the build-cache
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-q','cp', '/build_cache/dot_gradle.zip', '${_ANDROID_BUILD_CACHE}']
  waitFor:
    - gradle_build
  volumes:
    - name: 'build_cache'
      path: '/build_cache'
timeout: 1200s
