steps:
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: "bash"
  args: 
  - '-c'
  - |
    gsutil rsync -d -r "${_LICENSES_BUCKET}" licenses || exit 0
  id: copy-licenses
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/android-builder'
  - "--build-arg"
  - "ANDROID_SDK_LICENSE=${_ANDROID_SDK_LICENSE}"
  - '.'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/android-sdk-base'
  waitFor: 
  - copy-licenses
images: ['gcr.io/$PROJECT_ID/android-builder']
timeout: 2000s
substitutions:
  _LICENSES_BUCKET: ''
  _ANDROID_SDK_LICENSE: ''
